services:
  # Server service configuration
  - type: web
    name: listener-server
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    # Health check endpoint (matches server.ts)
    healthCheckPath: /healthz
    
    # Environment variables that need to be set in Render dashboard:
    # - SUPABASE_URL
    # - SUPABASE_ANON_KEY
    # - SUPABASE_SERVICE_ROLE_KEY
    # - DEEPGRAM_API_KEY
    # - SPOTIFY_CLIENT_ID
    # - SPOTIFY_CLIENT_SECRET
    # Add other environment variables as needed 